name: flutter_application_2
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  provider: ^6.1.1
  path_provider: ^2.1.2
  path: ^1.8.3
  sqflite: ^2.3.0
  firebase_core: ^2.25.0
  firebase_auth: ^4.17.0
  firebase_ui_auth: ^1.12.1
  firebase_database: ^10.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  assets:
    - images/lake.jpg

  uses-material-design: true
